"""
app/core/bundle/index_builder.py — OKF index.md Generator
==========================================================
Reads all OKF files in a bundle and auto-generates the master index.md.
The index.md is the FIRST thing the agent reads — it's the table of contents
for the entire knowledge bundle.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from app.core.bundle.manager import get_bundle_path, get_all_metadata
from app.utils.file_utils import safe_write


def build_index(repo_name: str) -> Path:
    """
    Generate (or regenerate) the index.md for a bundle.
    Groups files by their `type` field and creates a linked table of contents.

    Args:
        repo_name: The bundle slug.

    Returns:
        Path to the written index.md file.
    """
    all_files = get_all_metadata(repo_name)
    bundle_root = get_bundle_path(repo_name)

    # Skip index.md and log.md themselves
    files = [f for f in all_files if f.filename not in ("index.md", "log.md")]

    # Group by type
    groups: dict[str, list] = {}
    for f in files:
        groups.setdefault(f.type, []).append(f)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# OKF Bundle Index — `{repo_name}`",
        "",
        f"> Auto-generated by CodeMind on {now}  ",
        f"> **{len(files)} concept files** documented across **{len(groups)} categories**",
        "",
        "---",
        "",
    ]

    # ── Navigation table ─────────────────────────────────────────────────────
    lines.append("## 📂 Categories")
    lines.append("")
    for type_name in sorted(groups.keys()):
        count = len(groups[type_name])
        anchor = type_name.lower().replace(" ", "-")
        lines.append(f"- [{_emoji(type_name)} {type_name.title()}](#{anchor}) — {count} file(s)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Per-type sections ────────────────────────────────────────────────────
    for type_name in sorted(groups.keys()):
        type_files = groups[type_name]
        lines.append(f"## {_emoji(type_name)} {type_name.title()}")
        lines.append("")

        for f in sorted(type_files, key=lambda x: x.title):
            link = f"[{f.title}](./{f.filename})"
            description = f.description or "_No description provided._"
            tags_str = (
                " · ".join(f"`{t}`" for t in f.tags[:4]) if f.tags else ""
            )
            lines.append(f"### {link}")
            lines.append(f"{description}")
            if tags_str:
                lines.append(f"**Tags:** {tags_str}")
            if f.depends_on:
                dep_links = ", ".join(
                    f"[{d}](./{d})" for d in f.depends_on[:5]
                )
                lines.append(f"**Depends on:** {dep_links}")
            lines.append("")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        "_This index is automatically regenerated whenever the bundle is updated._  ",
        f"_See [log.md](./log.md) for change history._",
        "",
    ]

    content = "\n".join(lines)
    index_path = bundle_root / "index.md"
    safe_write(index_path, content)
    return index_path


def _emoji(type_name: str) -> str:
    """Return a relevant emoji for each OKF concept type."""
    mapping = {
        "module": "🔧",
        "architecture": "🏗️",
        "concept": "💡",
        "api": "🌐",
        "database": "🗄️",
        "config": "⚙️",
        "test": "🧪",
        "unknown": "📄",
    }
    return mapping.get(type_name.lower(), "📄")


def append_to_log(repo_name: str, message: str) -> None:
    """
    Append a timestamped entry to the bundle's log.md.
    Keeps a human-readable change history of the knowledge base.
    """
    bundle_root = get_bundle_path(repo_name)
    log_path = bundle_root / "log.md"

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    entry = f"\n- `{timestamp}` — {message}"

    if log_path.exists():
        existing = log_path.read_text(encoding="utf-8")
        safe_write(log_path, existing + entry)
    else:
        header = "# OKF Bundle Change Log\n\n_Auto-generated by CodeMind._\n"
        safe_write(log_path, header + entry)
